In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[10, 16]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[7, 5], [10, 16], [7, 26], [3, 15, 5], [29, 10, 17], [12, 5], [9, 10, 26], [2, 28], [2, 26], [22, 24]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 7  5  0  0]
 [10 16  0  0]
 [ 7 26  0  0]
 [ 3 15  5  0]
 [29 10 17  0]
 [12  5  0  0]
 [ 9 10 26  0]
 [ 2 28  0  0]
 [ 2 26  0  0]
 [22 24  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 20)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 106ms/step - loss: 0.6346 - accuracy: 0.9000


0.8999999761581421

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [12]:
weights[13]

array([ 0.01735398, -0.04293806,  0.00655047, -0.02153254,  0.00715277],
      dtype=float32)

In [13]:
weights[16]

array([-0.06076037,  0.02380128, -0.0177911 ,  0.0381032 ,  0.01754763],
      dtype=float32)

In [15]:
weights[one_hot("amazing restaurant",30)]

array([[ 0.08589151,  0.07235452,  0.04895287, -0.02244926, -0.01127691],
       [-0.06076037,  0.02380128, -0.0177911 ,  0.0381032 ,  0.01754763]],
      dtype=float32)

In [16]:
weights[0]

array([ 0.08643048, -0.00051666, -0.02594478, -0.02847511,  0.03561034],
      dtype=float32)

In [17]:
weights[1]

array([-0.04329312,  0.03716639, -0.02643392, -0.01560347,  0.01085376],
      dtype=float32)